version: '2'
services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/srv/static
  web:
    build: .
    ports:
      - 9000:9000
    volumes:
      - .:/app
      - /app/vendor
    depends_on:
      - postgres
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: deskmo
      POSTGRES_DB: deskmo
